/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatistikRouteImport } from './routes/statistik'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukIndexRouteImport } from './routes/produk/index'
import { Route as BeritaIndexRouteImport } from './routes/berita/index'
import { Route as ProdukSlugRouteImport } from './routes/produk/$slug'
import { Route as BeritaPengumumanRouteImport } from './routes/berita/pengumuman'
import { Route as BeritaSlugRouteImport } from './routes/berita/$slug'
import { Route as ApiSplatRouteImport } from './routes/api/$'

const StatistikRoute = StatistikRouteImport.update({
  id: '/statistik',
  path: '/statistik',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIndexRoute = ProdukIndexRouteImport.update({
  id: '/produk/',
  path: '/produk/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaIndexRoute = BeritaIndexRouteImport.update({
  id: '/berita/',
  path: '/berita/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaPengumumanRoute = BeritaPengumumanRouteImport.update({
  id: '/berita/pengumuman',
  path: '/berita/pengumuman',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaSlugRoute = BeritaSlugRouteImport.update({
  id: '/berita/$slug',
  path: '/berita/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/profil': typeof ProfilRoute
  '/statistik': typeof StatistikRoute
  '/api/$': typeof ApiSplatRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/berita/pengumuman': typeof BeritaPengumumanRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/berita/': typeof BeritaIndexRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/profil': typeof ProfilRoute
  '/statistik': typeof StatistikRoute
  '/api/$': typeof ApiSplatRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/berita/pengumuman': typeof BeritaPengumumanRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/berita': typeof BeritaIndexRoute
  '/produk': typeof ProdukIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/profil': typeof ProfilRoute
  '/statistik': typeof StatistikRoute
  '/api/$': typeof ApiSplatRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/berita/pengumuman': typeof BeritaPengumumanRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/berita/': typeof BeritaIndexRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galeri'
    | '/profil'
    | '/statistik'
    | '/api/$'
    | '/berita/$slug'
    | '/berita/pengumuman'
    | '/produk/$slug'
    | '/berita/'
    | '/produk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeri'
    | '/profil'
    | '/statistik'
    | '/api/$'
    | '/berita/$slug'
    | '/berita/pengumuman'
    | '/produk/$slug'
    | '/berita'
    | '/produk'
  id:
    | '__root__'
    | '/'
    | '/galeri'
    | '/profil'
    | '/statistik'
    | '/api/$'
    | '/berita/$slug'
    | '/berita/pengumuman'
    | '/produk/$slug'
    | '/berita/'
    | '/produk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriRoute: typeof GaleriRoute
  ProfilRoute: typeof ProfilRoute
  StatistikRoute: typeof StatistikRoute
  ApiSplatRoute: typeof ApiSplatRoute
  BeritaSlugRoute: typeof BeritaSlugRoute
  BeritaPengumumanRoute: typeof BeritaPengumumanRoute
  ProdukSlugRoute: typeof ProdukSlugRoute
  BeritaIndexRoute: typeof BeritaIndexRoute
  ProdukIndexRoute: typeof ProdukIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistik': {
      id: '/statistik'
      path: '/statistik'
      fullPath: '/statistik'
      preLoaderRoute: typeof StatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/': {
      id: '/produk/'
      path: '/produk'
      fullPath: '/produk/'
      preLoaderRoute: typeof ProdukIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/': {
      id: '/berita/'
      path: '/berita'
      fullPath: '/berita/'
      preLoaderRoute: typeof BeritaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$slug': {
      id: '/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/pengumuman': {
      id: '/berita/pengumuman'
      path: '/berita/pengumuman'
      fullPath: '/berita/pengumuman'
      preLoaderRoute: typeof BeritaPengumumanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/$slug': {
      id: '/berita/$slug'
      path: '/berita/$slug'
      fullPath: '/berita/$slug'
      preLoaderRoute: typeof BeritaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriRoute: GaleriRoute,
  ProfilRoute: ProfilRoute,
  StatistikRoute: StatistikRoute,
  ApiSplatRoute: ApiSplatRoute,
  BeritaSlugRoute: BeritaSlugRoute,
  BeritaPengumumanRoute: BeritaPengumumanRoute,
  ProdukSlugRoute: ProdukSlugRoute,
  BeritaIndexRoute: BeritaIndexRoute,
  ProdukIndexRoute: ProdukIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
