/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PengaduanRouteImport } from './routes/pengaduan'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukIndexRouteImport } from './routes/produk/index'
import { Route as BeritaIndexRouteImport } from './routes/berita/index'
import { Route as StatistikSdgsRouteImport } from './routes/statistik/sdgs'
import { Route as StatistikKependudukanRouteImport } from './routes/statistik/kependudukan'
import { Route as StatistikIdmRouteImport } from './routes/statistik/idm'
import { Route as PublikasiApbdesRouteImport } from './routes/publikasi/apbdes'
import { Route as ProfilStrukturOrganisasiRouteImport } from './routes/profil/struktur-organisasi'
import { Route as ProfilProfilDesaRouteImport } from './routes/profil/profil-desa'
import { Route as ProfilPetaDesaRouteImport } from './routes/profil/peta-desa'
import { Route as ProfilGeografiDesaRouteImport } from './routes/profil/geografi-desa'
import { Route as ProfilFasilitasUmumRouteImport } from './routes/profil/fasilitas-umum'
import { Route as ProdukSlugRouteImport } from './routes/produk/$slug'
import { Route as LembagaSlugRouteImport } from './routes/lembaga/$slug'
import { Route as InformasiAgendaRouteImport } from './routes/informasi/agenda'
import { Route as BeritaSlugRouteImport } from './routes/berita/$slug'
import { Route as ApiSplatRouteImport } from './routes/api/$'

const PengaduanRoute = PengaduanRouteImport.update({
  id: '/pengaduan',
  path: '/pengaduan',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIndexRoute = ProdukIndexRouteImport.update({
  id: '/produk/',
  path: '/produk/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaIndexRoute = BeritaIndexRouteImport.update({
  id: '/berita/',
  path: '/berita/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistikSdgsRoute = StatistikSdgsRouteImport.update({
  id: '/statistik/sdgs',
  path: '/statistik/sdgs',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistikKependudukanRoute = StatistikKependudukanRouteImport.update({
  id: '/statistik/kependudukan',
  path: '/statistik/kependudukan',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistikIdmRoute = StatistikIdmRouteImport.update({
  id: '/statistik/idm',
  path: '/statistik/idm',
  getParentRoute: () => rootRouteImport,
} as any)
const PublikasiApbdesRoute = PublikasiApbdesRouteImport.update({
  id: '/publikasi/apbdes',
  path: '/publikasi/apbdes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilStrukturOrganisasiRoute =
  ProfilStrukturOrganisasiRouteImport.update({
    id: '/profil/struktur-organisasi',
    path: '/profil/struktur-organisasi',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfilProfilDesaRoute = ProfilProfilDesaRouteImport.update({
  id: '/profil/profil-desa',
  path: '/profil/profil-desa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilPetaDesaRoute = ProfilPetaDesaRouteImport.update({
  id: '/profil/peta-desa',
  path: '/profil/peta-desa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilGeografiDesaRoute = ProfilGeografiDesaRouteImport.update({
  id: '/profil/geografi-desa',
  path: '/profil/geografi-desa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilFasilitasUmumRoute = ProfilFasilitasUmumRouteImport.update({
  id: '/profil/fasilitas-umum',
  path: '/profil/fasilitas-umum',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LembagaSlugRoute = LembagaSlugRouteImport.update({
  id: '/lembaga/$slug',
  path: '/lembaga/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiAgendaRoute = InformasiAgendaRouteImport.update({
  id: '/informasi/agenda',
  path: '/informasi/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaSlugRoute = BeritaSlugRouteImport.update({
  id: '/berita/$slug',
  path: '/berita/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/pengaduan': typeof PengaduanRoute
  '/api/$': typeof ApiSplatRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/informasi/agenda': typeof InformasiAgendaRoute
  '/lembaga/$slug': typeof LembagaSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/profil/fasilitas-umum': typeof ProfilFasilitasUmumRoute
  '/profil/geografi-desa': typeof ProfilGeografiDesaRoute
  '/profil/peta-desa': typeof ProfilPetaDesaRoute
  '/profil/profil-desa': typeof ProfilProfilDesaRoute
  '/profil/struktur-organisasi': typeof ProfilStrukturOrganisasiRoute
  '/publikasi/apbdes': typeof PublikasiApbdesRoute
  '/statistik/idm': typeof StatistikIdmRoute
  '/statistik/kependudukan': typeof StatistikKependudukanRoute
  '/statistik/sdgs': typeof StatistikSdgsRoute
  '/berita/': typeof BeritaIndexRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/pengaduan': typeof PengaduanRoute
  '/api/$': typeof ApiSplatRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/informasi/agenda': typeof InformasiAgendaRoute
  '/lembaga/$slug': typeof LembagaSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/profil/fasilitas-umum': typeof ProfilFasilitasUmumRoute
  '/profil/geografi-desa': typeof ProfilGeografiDesaRoute
  '/profil/peta-desa': typeof ProfilPetaDesaRoute
  '/profil/profil-desa': typeof ProfilProfilDesaRoute
  '/profil/struktur-organisasi': typeof ProfilStrukturOrganisasiRoute
  '/publikasi/apbdes': typeof PublikasiApbdesRoute
  '/statistik/idm': typeof StatistikIdmRoute
  '/statistik/kependudukan': typeof StatistikKependudukanRoute
  '/statistik/sdgs': typeof StatistikSdgsRoute
  '/berita': typeof BeritaIndexRoute
  '/produk': typeof ProdukIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/pengaduan': typeof PengaduanRoute
  '/api/$': typeof ApiSplatRoute
  '/berita/$slug': typeof BeritaSlugRoute
  '/informasi/agenda': typeof InformasiAgendaRoute
  '/lembaga/$slug': typeof LembagaSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/profil/fasilitas-umum': typeof ProfilFasilitasUmumRoute
  '/profil/geografi-desa': typeof ProfilGeografiDesaRoute
  '/profil/peta-desa': typeof ProfilPetaDesaRoute
  '/profil/profil-desa': typeof ProfilProfilDesaRoute
  '/profil/struktur-organisasi': typeof ProfilStrukturOrganisasiRoute
  '/publikasi/apbdes': typeof PublikasiApbdesRoute
  '/statistik/idm': typeof StatistikIdmRoute
  '/statistik/kependudukan': typeof StatistikKependudukanRoute
  '/statistik/sdgs': typeof StatistikSdgsRoute
  '/berita/': typeof BeritaIndexRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galeri'
    | '/pengaduan'
    | '/api/$'
    | '/berita/$slug'
    | '/informasi/agenda'
    | '/lembaga/$slug'
    | '/produk/$slug'
    | '/profil/fasilitas-umum'
    | '/profil/geografi-desa'
    | '/profil/peta-desa'
    | '/profil/profil-desa'
    | '/profil/struktur-organisasi'
    | '/publikasi/apbdes'
    | '/statistik/idm'
    | '/statistik/kependudukan'
    | '/statistik/sdgs'
    | '/berita/'
    | '/produk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeri'
    | '/pengaduan'
    | '/api/$'
    | '/berita/$slug'
    | '/informasi/agenda'
    | '/lembaga/$slug'
    | '/produk/$slug'
    | '/profil/fasilitas-umum'
    | '/profil/geografi-desa'
    | '/profil/peta-desa'
    | '/profil/profil-desa'
    | '/profil/struktur-organisasi'
    | '/publikasi/apbdes'
    | '/statistik/idm'
    | '/statistik/kependudukan'
    | '/statistik/sdgs'
    | '/berita'
    | '/produk'
  id:
    | '__root__'
    | '/'
    | '/galeri'
    | '/pengaduan'
    | '/api/$'
    | '/berita/$slug'
    | '/informasi/agenda'
    | '/lembaga/$slug'
    | '/produk/$slug'
    | '/profil/fasilitas-umum'
    | '/profil/geografi-desa'
    | '/profil/peta-desa'
    | '/profil/profil-desa'
    | '/profil/struktur-organisasi'
    | '/publikasi/apbdes'
    | '/statistik/idm'
    | '/statistik/kependudukan'
    | '/statistik/sdgs'
    | '/berita/'
    | '/produk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriRoute: typeof GaleriRoute
  PengaduanRoute: typeof PengaduanRoute
  ApiSplatRoute: typeof ApiSplatRoute
  BeritaSlugRoute: typeof BeritaSlugRoute
  InformasiAgendaRoute: typeof InformasiAgendaRoute
  LembagaSlugRoute: typeof LembagaSlugRoute
  ProdukSlugRoute: typeof ProdukSlugRoute
  ProfilFasilitasUmumRoute: typeof ProfilFasilitasUmumRoute
  ProfilGeografiDesaRoute: typeof ProfilGeografiDesaRoute
  ProfilPetaDesaRoute: typeof ProfilPetaDesaRoute
  ProfilProfilDesaRoute: typeof ProfilProfilDesaRoute
  ProfilStrukturOrganisasiRoute: typeof ProfilStrukturOrganisasiRoute
  PublikasiApbdesRoute: typeof PublikasiApbdesRoute
  StatistikIdmRoute: typeof StatistikIdmRoute
  StatistikKependudukanRoute: typeof StatistikKependudukanRoute
  StatistikSdgsRoute: typeof StatistikSdgsRoute
  BeritaIndexRoute: typeof BeritaIndexRoute
  ProdukIndexRoute: typeof ProdukIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pengaduan': {
      id: '/pengaduan'
      path: '/pengaduan'
      fullPath: '/pengaduan'
      preLoaderRoute: typeof PengaduanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/': {
      id: '/produk/'
      path: '/produk'
      fullPath: '/produk/'
      preLoaderRoute: typeof ProdukIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/': {
      id: '/berita/'
      path: '/berita'
      fullPath: '/berita/'
      preLoaderRoute: typeof BeritaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistik/sdgs': {
      id: '/statistik/sdgs'
      path: '/statistik/sdgs'
      fullPath: '/statistik/sdgs'
      preLoaderRoute: typeof StatistikSdgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistik/kependudukan': {
      id: '/statistik/kependudukan'
      path: '/statistik/kependudukan'
      fullPath: '/statistik/kependudukan'
      preLoaderRoute: typeof StatistikKependudukanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistik/idm': {
      id: '/statistik/idm'
      path: '/statistik/idm'
      fullPath: '/statistik/idm'
      preLoaderRoute: typeof StatistikIdmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publikasi/apbdes': {
      id: '/publikasi/apbdes'
      path: '/publikasi/apbdes'
      fullPath: '/publikasi/apbdes'
      preLoaderRoute: typeof PublikasiApbdesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/struktur-organisasi': {
      id: '/profil/struktur-organisasi'
      path: '/profil/struktur-organisasi'
      fullPath: '/profil/struktur-organisasi'
      preLoaderRoute: typeof ProfilStrukturOrganisasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/profil-desa': {
      id: '/profil/profil-desa'
      path: '/profil/profil-desa'
      fullPath: '/profil/profil-desa'
      preLoaderRoute: typeof ProfilProfilDesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/peta-desa': {
      id: '/profil/peta-desa'
      path: '/profil/peta-desa'
      fullPath: '/profil/peta-desa'
      preLoaderRoute: typeof ProfilPetaDesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/geografi-desa': {
      id: '/profil/geografi-desa'
      path: '/profil/geografi-desa'
      fullPath: '/profil/geografi-desa'
      preLoaderRoute: typeof ProfilGeografiDesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/fasilitas-umum': {
      id: '/profil/fasilitas-umum'
      path: '/profil/fasilitas-umum'
      fullPath: '/profil/fasilitas-umum'
      preLoaderRoute: typeof ProfilFasilitasUmumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$slug': {
      id: '/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lembaga/$slug': {
      id: '/lembaga/$slug'
      path: '/lembaga/$slug'
      fullPath: '/lembaga/$slug'
      preLoaderRoute: typeof LembagaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi/agenda': {
      id: '/informasi/agenda'
      path: '/informasi/agenda'
      fullPath: '/informasi/agenda'
      preLoaderRoute: typeof InformasiAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita/$slug': {
      id: '/berita/$slug'
      path: '/berita/$slug'
      fullPath: '/berita/$slug'
      preLoaderRoute: typeof BeritaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriRoute: GaleriRoute,
  PengaduanRoute: PengaduanRoute,
  ApiSplatRoute: ApiSplatRoute,
  BeritaSlugRoute: BeritaSlugRoute,
  InformasiAgendaRoute: InformasiAgendaRoute,
  LembagaSlugRoute: LembagaSlugRoute,
  ProdukSlugRoute: ProdukSlugRoute,
  ProfilFasilitasUmumRoute: ProfilFasilitasUmumRoute,
  ProfilGeografiDesaRoute: ProfilGeografiDesaRoute,
  ProfilPetaDesaRoute: ProfilPetaDesaRoute,
  ProfilProfilDesaRoute: ProfilProfilDesaRoute,
  ProfilStrukturOrganisasiRoute: ProfilStrukturOrganisasiRoute,
  PublikasiApbdesRoute: PublikasiApbdesRoute,
  StatistikIdmRoute: StatistikIdmRoute,
  StatistikKependudukanRoute: StatistikKependudukanRoute,
  StatistikSdgsRoute: StatistikSdgsRoute,
  BeritaIndexRoute: BeritaIndexRoute,
  ProdukIndexRoute: ProdukIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
